ALTER TABLE STUDENT MODIFY COLUMN birthday NOT NULL;
ALTER TABLE MARK MODIFY COLUMN mark INT CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE MARK MODIFY COLUMN student_id NOT NULL;
ALTER TABLE MARK MODIFY COLUMN subject_id NOT NULL;
ALTER TABLE SUBJECT MODIFY COLUMN INT CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE PAYMENTTYPE MODIFY COLUMN name UNIQUE;
ALTER TABLE PAYMENT MODIFY COLUMN type_id NOT NULL;
ALTER TABLE PAYMENT MODIFY COLUMN amount NOT NULL;
ALTER TABLE PAYMENT MODIFY COLUMN date NOT NULL;