ALTER TABLE Student MODIFY COLUMN birthday DATE NOT NULL;
ALTER TABLE Mark MODIFY COLUMN mark INT CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE Mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE Mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE Subject MODIFY COLUMN grade INT CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE PaymentType MODIFY COLUMN name VARCHAR(255) UNIQUE;
ALTER TABLE Payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE Payment MODIFY COLUMN amount DECIMAL NOT NULL;
ALTER TABLE Payment MODIFY COLUMN payment_date DATETIME NOT NULL;